import { MigrationInterface, QueryRunner } from "typeorm";

export class AddAllTables1780215665810 implements MigrationInterface {
    name = 'AddAllTables1780215665810'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."user_social_channel_enum" AS ENUM('GOOGLE', 'APPLE', 'NONE')`);
        await queryRunner.query(`CREATE TYPE "public"."user_account_auth_status_enum" AS ENUM('PASSWORD_RESET', 'OK')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "identifier" character varying NOT NULL, "social_channel" "public"."user_social_channel_enum" NOT NULL DEFAULT 'NONE', "account_auth_status" "public"."user_account_auth_status_enum", "social_channel_id" character varying, "password" character varying, "password_reset_date" TIMESTAMP, CONSTRAINT "UQ_7efb296eadd258e554e84fa6eb6" UNIQUE ("identifier"), CONSTRAINT "UQ_7efb296eadd258e554e84fa6eb6" UNIQUE ("identifier"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cace4a159ff9f2512dd4237376" ON "user" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7efb296eadd258e554e84fa6eb" ON "user" ("identifier") `);
        await queryRunner.query(`CREATE TABLE "user_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "company" character varying NOT NULL, "phone_number" character varying NOT NULL, "profile_picture" character varying(255), "user_id" uuid NOT NULL, CONSTRAINT "REL_59c55ac40f267d450246040899" UNIQUE ("user_id"), CONSTRAINT "PK_273a06d6cdc2085ee1ce7638b24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_273a06d6cdc2085ee1ce7638b2" ON "user_info" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."resource_type_enum" AS ENUM('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT')`);
        await queryRunner.query(`CREATE TYPE "public"."resource_mime_type_enum" AS ENUM('text/plain', 'text/html', 'application/json', 'application/xml', 'application/pdf', 'application/msword', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'image/jpeg', 'image/png', 'image/gif', 'audio/mpeg', 'audio/wav', 'video/mp4', 'video/mpeg')`);
        await queryRunner.query(`CREATE TABLE "resource" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "filename" character varying(255) NOT NULL, "type" "public"."resource_type_enum" NOT NULL, "url" text NOT NULL, "mime_type" "public"."resource_mime_type_enum" NOT NULL DEFAULT 'image/jpeg', "readonly" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_e2894a5867e06ae2e8889f1173f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e2894a5867e06ae2e8889f1173" ON "resource" ("id") `);
        await queryRunner.query(`CREATE TABLE "progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "completed" boolean NOT NULL DEFAULT false, "last_position" double precision NOT NULL DEFAULT '0', "user_id" uuid, "lesson_id" uuid, CONSTRAINT "PK_79abdfd87a688f9de756a162b6f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_79abdfd87a688f9de756a162b6" ON "progress" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ddcaca3a9db9d77105d51c02c2" ON "progress" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9e287419e37b04d545078d9c9b" ON "progress" ("user_id", "lesson_id") `);
        await queryRunner.query(`CREATE TABLE "lessons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying NOT NULL, "videoUrl" character varying NOT NULL, "notes" text, "order" integer NOT NULL, "description" text NOT NULL, "duration" integer NOT NULL, "module_id" uuid, CONSTRAINT "PK_9b9a8d455cac672d262d7275730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9b9a8d455cac672d262d727573" ON "lessons" ("id") `);
        await queryRunner.query(`CREATE TABLE "questions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "text" text NOT NULL, "options" jsonb NOT NULL DEFAULT '[]', "test_id" uuid NOT NULL, CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_08a6d4b0f49ff300bf3a0ca60a" ON "questions" ("id") `);
        await queryRunner.query(`CREATE TABLE "test_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "test_id" uuid NOT NULL, "score" double precision NOT NULL, "answers" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_e05ffc282586eb005bdbe62084b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e05ffc282586eb005bdbe62084" ON "test_submissions" ("id") `);
        await queryRunner.query(`CREATE TABLE "tests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying NOT NULL, "time_limit" integer NOT NULL DEFAULT '30', "allowed_attempts" integer NOT NULL DEFAULT '3', "module_id" uuid NOT NULL, CONSTRAINT "REL_8d21344ff33d0ceef2363eb8d7" UNIQUE ("module_id"), CONSTRAINT "PK_4301ca51edf839623386860aed2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4301ca51edf839623386860aed" ON "tests" ("id") `);
        await queryRunner.query(`CREATE TABLE "module" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying NOT NULL, "order" integer NOT NULL, "estimatedTime" character varying NOT NULL, "moduleDetails" text, "course_id" uuid, CONSTRAINT "PK_0e20d657f968b051e674fbe3117" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0e20d657f968b051e674fbe311" ON "module" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."enrollment_status_enum" AS ENUM('active', 'completed')`);
        await queryRunner.query(`CREATE TABLE "enrollment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "status" "public"."enrollment_status_enum" NOT NULL DEFAULT 'active', "user_id" uuid, "course_id" uuid, CONSTRAINT "PK_7e200c699fa93865cdcdd025885" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7e200c699fa93865cdcdd02588" ON "enrollment" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc17c7e94154a17e767b7674f1" ON "enrollment" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "instructor" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" character varying NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "profile_picture" text, "role" character varying(200) NOT NULL, "specialization" character varying(200) NOT NULL, "phone_number" character varying(200) NOT NULL, "bio" text, CONSTRAINT "UQ_6222960ab4f2b68e84bc00bfeeb" UNIQUE ("email"), CONSTRAINT "PK_ccc0348eefb581ca002c05ef2f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ccc0348eefb581ca002c05ef2f" ON "instructor" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6222960ab4f2b68e84bc00bfee" ON "instructor" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."course_pricingmodel_enum" AS ENUM('FREE', 'PAID')`);
        await queryRunner.query(`CREATE TYPE "public"."course_difficulty_enum" AS ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED')`);
        await queryRunner.query(`CREATE TABLE "course" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying NOT NULL, "description" text, "skillsGained" text, "expectedExperience" text, "thumbnail" character varying NOT NULL, "isPopular" boolean NOT NULL DEFAULT false, "provider" character varying NOT NULL DEFAULT 'Sentinel Prime K', "pricingModel" "public"."course_pricingmodel_enum" NOT NULL, "price" integer, "specialization" character varying, "enrolledCount" integer NOT NULL DEFAULT '0', "difficulty" "public"."course_difficulty_enum" NOT NULL, "approvalRate" integer, "languages" text, "instructor_id" uuid, CONSTRAINT "PK_bf95180dd756fd204fb01ce4916" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bf95180dd756fd204fb01ce491" ON "course" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."transaction_currency_enum" AS ENUM('EUR', 'AED', 'AFN', 'XCD', 'ALL', 'AMD', 'AOA', 'ARS', 'USD', 'AUD', 'AWG', 'AZN', 'BAM', 'BBD', 'BDT', 'XOF', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BOV', 'BRL', 'BSD', 'BTN', 'INR', 'NOK', 'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'XAF', 'CHF', 'CHE', 'CHW', 'NZD', 'CLF', 'CLP', 'CNY', 'COP', 'CRC', 'CUP', 'CVE', 'ANG', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'MAD', 'MRU', 'ERN', 'ETB', 'FJD', 'FKP', 'GBP', 'GEL', 'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL', 'HTG', 'HUF', 'IDR', 'ILS', 'IQD', 'IRR', 'ISK', 'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KMF', 'KPW', 'KRW', 'KWD', 'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'ZAR', 'LYD', 'MDL', 'MGA', 'MKD', 'MMK', 'MNT', 'MOP', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZN', 'NAD', 'XPF', 'NGN', 'NIO', 'NPR', 'OMR', 'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLL', 'SOS', 'SRD', 'SSP', 'STN', 'SVC', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY', 'TTD', 'TWD', 'TZS', 'UAH', 'UGX', 'USN', 'USS', 'UYI', 'UYU', 'UZS', 'VES', 'VND', 'VUV', 'WST', 'YER', 'ZMW')`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_payment_mode_enum" AS ENUM('MOBILE_MONEY', 'BANK', 'CARD')`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_status_enum" AS ENUM('initiated', 'pending', 'success', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_transaction_type_enum" AS ENUM('PAYMENT', 'REFUND', 'PAYOUT', 'SUBSCRIPTION')`);
        await queryRunner.query(`CREATE TABLE "transaction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "amount" integer NOT NULL, "currency" "public"."transaction_currency_enum" NOT NULL, "payment_mode" "public"."transaction_payment_mode_enum", "provider" character varying NOT NULL, "providerRef" character varying NOT NULL, "status" "public"."transaction_status_enum" NOT NULL DEFAULT 'initiated', "transaction_type" "public"."transaction_transaction_type_enum" NOT NULL DEFAULT 'PAYMENT', "card_brand" character varying, "card_last4" character varying, "user_id" uuid, "course_id" uuid, CONSTRAINT "PK_89eadb93a89810556e1cbcd6ab9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89eadb93a89810556e1cbcd6ab" ON "transaction" ("id") `);
        await queryRunner.query(`CREATE TABLE "user-card" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "card_token" character varying NOT NULL, "last4" character varying(4) NOT NULL, "brand" character varying NOT NULL, "exp_month" integer NOT NULL, "exp_year" integer NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "user_id" uuid NOT NULL, CONSTRAINT "UQ_7abd0069e70ac4e0c8d1dad4a2f" UNIQUE ("card_token"), CONSTRAINT "PK_1e62935305aff4508df1ac91575" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1e62935305aff4508df1ac9157" ON "user-card" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."plan_currency_enum" AS ENUM('EUR', 'AED', 'AFN', 'XCD', 'ALL', 'AMD', 'AOA', 'ARS', 'USD', 'AUD', 'AWG', 'AZN', 'BAM', 'BBD', 'BDT', 'XOF', 'BGN', 'BHD', 'BIF', 'BMD', 'BND', 'BOB', 'BOV', 'BRL', 'BSD', 'BTN', 'INR', 'NOK', 'BWP', 'BYN', 'BZD', 'CAD', 'CDF', 'XAF', 'CHF', 'CHE', 'CHW', 'NZD', 'CLF', 'CLP', 'CNY', 'COP', 'CRC', 'CUP', 'CVE', 'ANG', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'MAD', 'MRU', 'ERN', 'ETB', 'FJD', 'FKP', 'GBP', 'GEL', 'GHS', 'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL', 'HTG', 'HUF', 'IDR', 'ILS', 'IQD', 'IRR', 'ISK', 'JMD', 'JOD', 'JPY', 'KES', 'KGS', 'KHR', 'KMF', 'KPW', 'KRW', 'KWD', 'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL', 'ZAR', 'LYD', 'MDL', 'MGA', 'MKD', 'MMK', 'MNT', 'MOP', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR', 'MZN', 'NAD', 'XPF', 'NGN', 'NIO', 'NPR', 'OMR', 'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR', 'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLL', 'SOS', 'SRD', 'SSP', 'STN', 'SVC', 'SYP', 'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY', 'TTD', 'TWD', 'TZS', 'UAH', 'UGX', 'USN', 'USS', 'UYI', 'UYU', 'UZS', 'VES', 'VND', 'VUV', 'WST', 'YER', 'ZMW')`);
        await queryRunner.query(`CREATE TABLE "plan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "price" integer NOT NULL, "currency" "public"."plan_currency_enum" NOT NULL, "interval" character varying NOT NULL, "trialDays" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_54a2b686aed3b637654bf7ddbb3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54a2b686aed3b637654bf7ddbb" ON "plan" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."subscription_status_enum" AS ENUM('active', 'trial', 'canceled', 'expired')`);
        await queryRunner.query(`CREATE TABLE "subscription" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "transactionId" character varying NOT NULL, "status" "public"."subscription_status_enum" NOT NULL, "trialEndsAt" TIMESTAMP, "subscribedAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP, "userId" uuid, "planId" uuid, CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c3e00ebd02103caa1174cd5d9" ON "subscription" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d964c8a3d314020a233101f7fc" ON "subscription" ("transactionId") `);
        await queryRunner.query(`CREATE TYPE "public"."review_entity_type_enum" AS ENUM('INSTRUCTOR', 'COURSE', 'LESSON')`);
        await queryRunner.query(`CREATE TABLE "review" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "entity_type" "public"."review_entity_type_enum" NOT NULL, "entity_id" character varying(255) NOT NULL, "rating" integer NOT NULL, "comment" text NOT NULL, "reviewer_id" uuid NOT NULL, CONSTRAINT "PK_2e4299a343a81574217255c00ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2e4299a343a81574217255c00c" ON "review" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f8adca6682f8238c64d767c9d" ON "review" ("reviewer_id") `);
        await queryRunner.query(`CREATE TYPE "public"."otp_identifier_type_enum" AS ENUM('EMAIL', 'PHONE')`);
        await queryRunner.query(`CREATE TYPE "public"."otp_status_enum" AS ENUM('ACTIVE', 'USED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "otp" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "identifier" character varying NOT NULL, "identifier_type" "public"."otp_identifier_type_enum" NOT NULL, "status" "public"."otp_status_enum" NOT NULL DEFAULT 'ACTIVE', "expiresAt" TIMESTAMP NOT NULL, "code" character varying(10) NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "user_id" uuid NOT NULL, CONSTRAINT "PK_32556d9d7b22031d7d0e1fd6723" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32556d9d7b22031d7d0e1fd672" ON "otp" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."contact_identifier_type_enum" AS ENUM('EMAIL', 'PHONE')`);
        await queryRunner.query(`CREATE TYPE "public"."contact_status_enum" AS ENUM('VERIFIED', 'PENDING', 'NOT_STARTED')`);
        await queryRunner.query(`CREATE TABLE "contact" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "identifier" character varying NOT NULL, "identifier_type" "public"."contact_identifier_type_enum" NOT NULL, "status" "public"."contact_status_enum" NOT NULL DEFAULT 'NOT_STARTED', "user_id" uuid NOT NULL, CONSTRAINT "UQ_d7aa7ba8aa0003605953b39a7fc" UNIQUE ("identifier"), CONSTRAINT "PK_2cbbe00f59ab6b3bb5b8d19f989" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cbbe00f59ab6b3bb5b8d19f98" ON "contact" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."account_session_activity_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "account_session_activity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deviceType" character varying NOT NULL, "os" character varying NOT NULL, "status" "public"."account_session_activity_status_enum" NOT NULL DEFAULT 'ACTIVE', "userId" uuid, CONSTRAINT "PK_eee2acbeed16f65a8f56d49935d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eee2acbeed16f65a8f56d49935" ON "account_session_activity" ("id") `);
        await queryRunner.query(`CREATE TABLE "lessons_resource_resource" ("lessonsId" uuid NOT NULL, "resourceId" uuid NOT NULL, CONSTRAINT "PK_c7f71759e46839b221d254b6eef" PRIMARY KEY ("lessonsId", "resourceId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a90a532507ba31ad8e4e4533eb" ON "lessons_resource_resource" ("lessonsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7072d578b4d0ba7883085ba763" ON "lessons_resource_resource" ("resourceId") `);
        await queryRunner.query(`ALTER TABLE "user_info" ADD CONSTRAINT "FK_59c55ac40f267d450246040899e" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "progress" ADD CONSTRAINT "FK_ddcaca3a9db9d77105d51c02c24" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "progress" ADD CONSTRAINT "FK_ef62be61a6c4f69d0570bb5cc35" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_35fb2307535d90a6ed290af1f4a" FOREIGN KEY ("module_id") REFERENCES "module"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_b1f107600ed9ed81aba56edfcea" FOREIGN KEY ("test_id") REFERENCES "tests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_submissions" ADD CONSTRAINT "FK_c3072456d610b7077cb811a773a" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test_submissions" ADD CONSTRAINT "FK_983b7d564ea222e873cb9aeb88d" FOREIGN KEY ("test_id") REFERENCES "tests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tests" ADD CONSTRAINT "FK_8d21344ff33d0ceef2363eb8d75" FOREIGN KEY ("module_id") REFERENCES "module"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "module" ADD CONSTRAINT "FK_915ad25970ccbfeb9e16e82c181" FOREIGN KEY ("course_id") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_fc17c7e94154a17e767b7674f12" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_dd1ce01d1164c8bbdda052ced74" FOREIGN KEY ("course_id") REFERENCES "course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_deca5c9911b3b2100b361060826" FOREIGN KEY ("instructor_id") REFERENCES "instructor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_b4a3d92d5dde30f3ab5c34c5862" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_f4b24f48fad36abdea7cb251014" FOREIGN KEY ("course_id") REFERENCES "course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user-card" ADD CONSTRAINT "FK_a456db2c36e45a97a4b98f27a4f" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_cc906b4bc892b048f1b654d2aa0" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_6b6d0e4dc88105a4a11103dd2cd" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_2f8adca6682f8238c64d767c9d3" FOREIGN KEY ("reviewer_id") REFERENCES "user_info"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otp" ADD CONSTRAINT "FK_258d028d322ea3b856bf9f12f25" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact" ADD CONSTRAINT "FK_33d4fc93803e7192e150216fffb" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_session_activity" ADD CONSTRAINT "FK_e1f3e65f5f4d7d01e3fa5b53a7f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons_resource_resource" ADD CONSTRAINT "FK_a90a532507ba31ad8e4e4533eb8" FOREIGN KEY ("lessonsId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "lessons_resource_resource" ADD CONSTRAINT "FK_7072d578b4d0ba7883085ba763e" FOREIGN KEY ("resourceId") REFERENCES "resource"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "lessons_resource_resource" DROP CONSTRAINT "FK_7072d578b4d0ba7883085ba763e"`);
        await queryRunner.query(`ALTER TABLE "lessons_resource_resource" DROP CONSTRAINT "FK_a90a532507ba31ad8e4e4533eb8"`);
        await queryRunner.query(`ALTER TABLE "account_session_activity" DROP CONSTRAINT "FK_e1f3e65f5f4d7d01e3fa5b53a7f"`);
        await queryRunner.query(`ALTER TABLE "contact" DROP CONSTRAINT "FK_33d4fc93803e7192e150216fffb"`);
        await queryRunner.query(`ALTER TABLE "otp" DROP CONSTRAINT "FK_258d028d322ea3b856bf9f12f25"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_2f8adca6682f8238c64d767c9d3"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_6b6d0e4dc88105a4a11103dd2cd"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_cc906b4bc892b048f1b654d2aa0"`);
        await queryRunner.query(`ALTER TABLE "user-card" DROP CONSTRAINT "FK_a456db2c36e45a97a4b98f27a4f"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_f4b24f48fad36abdea7cb251014"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_b4a3d92d5dde30f3ab5c34c5862"`);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_deca5c9911b3b2100b361060826"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_dd1ce01d1164c8bbdda052ced74"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_fc17c7e94154a17e767b7674f12"`);
        await queryRunner.query(`ALTER TABLE "module" DROP CONSTRAINT "FK_915ad25970ccbfeb9e16e82c181"`);
        await queryRunner.query(`ALTER TABLE "tests" DROP CONSTRAINT "FK_8d21344ff33d0ceef2363eb8d75"`);
        await queryRunner.query(`ALTER TABLE "test_submissions" DROP CONSTRAINT "FK_983b7d564ea222e873cb9aeb88d"`);
        await queryRunner.query(`ALTER TABLE "test_submissions" DROP CONSTRAINT "FK_c3072456d610b7077cb811a773a"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_b1f107600ed9ed81aba56edfcea"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_35fb2307535d90a6ed290af1f4a"`);
        await queryRunner.query(`ALTER TABLE "progress" DROP CONSTRAINT "FK_ef62be61a6c4f69d0570bb5cc35"`);
        await queryRunner.query(`ALTER TABLE "progress" DROP CONSTRAINT "FK_ddcaca3a9db9d77105d51c02c24"`);
        await queryRunner.query(`ALTER TABLE "user_info" DROP CONSTRAINT "FK_59c55ac40f267d450246040899e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7072d578b4d0ba7883085ba763"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a90a532507ba31ad8e4e4533eb"`);
        await queryRunner.query(`DROP TABLE "lessons_resource_resource"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eee2acbeed16f65a8f56d49935"`);
        await queryRunner.query(`DROP TABLE "account_session_activity"`);
        await queryRunner.query(`DROP TYPE "public"."account_session_activity_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cbbe00f59ab6b3bb5b8d19f98"`);
        await queryRunner.query(`DROP TABLE "contact"`);
        await queryRunner.query(`DROP TYPE "public"."contact_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."contact_identifier_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32556d9d7b22031d7d0e1fd672"`);
        await queryRunner.query(`DROP TABLE "otp"`);
        await queryRunner.query(`DROP TYPE "public"."otp_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."otp_identifier_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f8adca6682f8238c64d767c9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e4299a343a81574217255c00c"`);
        await queryRunner.query(`DROP TABLE "review"`);
        await queryRunner.query(`DROP TYPE "public"."review_entity_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d964c8a3d314020a233101f7fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c3e00ebd02103caa1174cd5d9"`);
        await queryRunner.query(`DROP TABLE "subscription"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54a2b686aed3b637654bf7ddbb"`);
        await queryRunner.query(`DROP TABLE "plan"`);
        await queryRunner.query(`DROP TYPE "public"."plan_currency_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e62935305aff4508df1ac9157"`);
        await queryRunner.query(`DROP TABLE "user-card"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89eadb93a89810556e1cbcd6ab"`);
        await queryRunner.query(`DROP TABLE "transaction"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_transaction_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_payment_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_currency_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf95180dd756fd204fb01ce491"`);
        await queryRunner.query(`DROP TABLE "course"`);
        await queryRunner.query(`DROP TYPE "public"."course_difficulty_enum"`);
        await queryRunner.query(`DROP TYPE "public"."course_pricingmodel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6222960ab4f2b68e84bc00bfee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccc0348eefb581ca002c05ef2f"`);
        await queryRunner.query(`DROP TABLE "instructor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc17c7e94154a17e767b7674f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e200c699fa93865cdcdd02588"`);
        await queryRunner.query(`DROP TABLE "enrollment"`);
        await queryRunner.query(`DROP TYPE "public"."enrollment_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e20d657f968b051e674fbe311"`);
        await queryRunner.query(`DROP TABLE "module"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4301ca51edf839623386860aed"`);
        await queryRunner.query(`DROP TABLE "tests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e05ffc282586eb005bdbe62084"`);
        await queryRunner.query(`DROP TABLE "test_submissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08a6d4b0f49ff300bf3a0ca60a"`);
        await queryRunner.query(`DROP TABLE "questions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b9a8d455cac672d262d727573"`);
        await queryRunner.query(`DROP TABLE "lessons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e287419e37b04d545078d9c9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddcaca3a9db9d77105d51c02c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79abdfd87a688f9de756a162b6"`);
        await queryRunner.query(`DROP TABLE "progress"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2894a5867e06ae2e8889f1173"`);
        await queryRunner.query(`DROP TABLE "resource"`);
        await queryRunner.query(`DROP TYPE "public"."resource_mime_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."resource_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_273a06d6cdc2085ee1ce7638b2"`);
        await queryRunner.query(`DROP TABLE "user_info"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7efb296eadd258e554e84fa6eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cace4a159ff9f2512dd4237376"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_account_auth_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_social_channel_enum"`);
    }

}
