import { inject, injectable } from "tsyringe";
import { ReviewEntity } from "@domain/models/entities/review.entity";
import { CreateReviewPort } from "@ports/in/review/create-review.port";
import { ReviewPersistencePort } from "@ports/out/persistence/review.persistence";
import { EntityType } from "@common/global/types";

@injectable()
export class CreateReviewUseCase implements CreateReviewPort {
    constructor(
        @inject("ReviewPersistencePort")
        private reviewPersistencePort: ReviewPersistencePort
    ) {}

    async createReview(userId: string, courseId: string, rating: number, comment?: string): Promise<void> {
        const reviewEntity = new ReviewEntity(
            "", // ID generated by Database
            userId,
            rating,
            EntityType.COURSE,
            courseId,
            comment || ""
        );
        return this.reviewPersistencePort.create(userId, courseId, reviewEntity);
    }
}
